"""empty message

Revision ID: c2fc0da02491
Revises: 
Create Date: 2024-04-13 14:23:03.470147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fc0da02491'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('points_min', sa.Integer(), nullable=True),
    sa.Column('points_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('user_type', sa.Enum('user', 'company', name='myenum'), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('status_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['status_name'], ['status.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('treasures_hide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('tips', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('city_name', sa.String(), nullable=True),
    sa.Column('founded', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['city_name'], ['cities.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treasures_founded',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treasures_hide_id', sa.Integer(), nullable=False),
    sa.Column('user_found_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['treasures_hide_id'], ['treasures_hide.id'], ),
    sa.ForeignKeyConstraint(['user_found_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treasures_founded')
    op.drop_table('treasures_hide')
    op.drop_table('user')
    op.drop_table('status')
    op.drop_table('cities')
    # ### end Alembic commands ###
